var filme_sugestao = [
  "A Origem", 
  "Cidade de Deus", 
  "Clube da Luta",
  "Barbie e as Três Mosqueteiras", 
  "Coringa",
  "Barbie e o Castelo de Diamante",
  "De Volta para o Futuro", 
  "Forrest Gump", 
  "Gladiador",
  "Harry Potter e a Pedra Filosofal", 
  "Homem-Aranha: Através do Aranhaverso",
  "Interestelar", 
  "Matrix", 
  "Matrix Reloaded", 
  "Matrix Revolutions",
  "O Cavaleiro das Trevas", 
  "O Grande Lebowski", 
  "O Poderoso Chefão",
  "O Senhor dos Anéis: O Retorno do Rei", 
  "O Silêncio dos Inocentes",
  "Os Bons Companheiros", 
  "Parasita",
  "Star Wars: Episódio IV - Uma Nova Esperança", 
  "Toy Story 4",
  "Vingadores: Ultimato"
];