const filme_sugestao = [
  "O Poderoso Chefão",
  "Interestelar",
  "Clube da Luta",
  "Forrest Gump",
  "Matrix",
  "Matrix Reloaded",
  "Matrix Revolutions",
  "O Senhor dos Anéis: O Retorno do Rei",
  "Pulp Fiction",
  "O Cavaleiro das Trevas",
  "A Origem",
  "Os Bons Companheiros",
  "Parasita",
  "Vingadores: Ultimato",
  "O Silêncio dos Inocentes",
  "Coringa",
  "Toy Story",
  "Toy Story 2",
  "Toy Story 3",
  "Toy Story 4",
  "De Volta para o Futuro",
  "Gladiador",
  "O Grande Lebowski",
  "Cidade de Deus",
  "Harry Potter e a Pedra Filosofal",
  "Harry Potter e a Câmara Secreta",
  "Harry Potter e o Prisioneiro de Azkaban",
  "Harry Potter e o Cálice de Fogo",
  "Harry Potter e a Ordem da Fênix",
  "Harry Potter e o Enigma do Príncipe",
  "Harry Potter e os Relíquias da Morte - Parte 1",
  "Harry Potter e os Relíquias da Morte - Parte 2",
  "Star Wars: Episódio IV - Uma Nova Esperança",
  "Star Wars: Episódio V - O Império Contra-Ataca",
  "Star Wars: Episódio VI - O Retorno de Jedi",
  "Star Wars: Episódio VII - O Despertar da Força",
  "Star Wars: Episódio VIII - Os Últimos Jedi",
  "Star Wars: Episódio IX - A Ascensão Skywalker",
  "Homem-Aranha: Através do Aranhaverso",
];
